complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B,kB,MB,GB,TB,PB"
filesize_metric = true
nonzero_exit_errors = false
pivot_mode = "always"
prompt = "starship prompt"
rm_always_trash = "false"
skip_welcome_message = true
startup = ["alias ll = ls --long", "alias la = ls -a", "def df [] {sys | get disks | select mount total free}"]
table_mode = "other"

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "wd"
leading_trailing_space_bg = "white"
primitive_binary = "ub"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "wu"
primitive_decimal = "cyan_bold"
primitive_duration = "blue"
primitive_filesize = "cb"
primitive_int = "green_bold"
primitive_line = "white"
primitive_path = "white"
primitive_pattern = "white"
primitive_range = "green"
primitive_string = "w"
separator_color = "purple"

[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_match_method = "case-insensitive"
completion_prompt_limit = 100
completion_type = "list"
edit_mode = "emacs"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "character"
